FROM php:7.3.3-apache
RUN apt-get update && apt-get install -y libpq-dev
RUN apt-get install -y libpng-dev
RUN docker-php-ext-install pgsql pdo_pgsql
RUN docker-php-ext-install gd
RUN a2enmod rewrite
RUN service apache2 restart
